### ISSUE TITLE
So interesting work！However, can you provide more detail implementation of the code? And I also  find some of data (such as memorized_gpt) is missing. Would you like to share you whole training script so that we can easily follow your work. Thanks!

### ISSUE THREAD

**Issue by SJY8460** [vanessawu1022/OntoProbe-PLMs#1]

**Comment by vickywu1022** [comment]
Thank you so much for your interest on our work! I really appreciate you taking the time to review our implementation details. I've just uploaded the data and scripts to probe ChatGPT (also for BERT models) for your reference.
